"""add_reports_table

Revision ID: 0bd99d810ccc
Revises: g3g3g3g3g3g3
Create Date: 2026-07-12 10:56:58.013236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd99d810ccc'
down_revision = 'g3g3g3g3g3g3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_type'), ['target_type'], unique=False)

    with op.batch_alter_table('gigs', schema=None) as batch_op:
        batch_op.create_index('ix_gig_category_status', ['category', 'status'], unique=False)
        batch_op.create_index('ix_gig_client_status', ['client_id', 'status'], unique=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('ix_listing_category_status', ['category', 'status'], unique=False)
        batch_op.create_index('ix_listing_seller_status', ['seller_id', 'status'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_message_participants', ['sender_id', 'recipient_id'], unique=False)
        batch_op.create_index('ix_message_recipient_read', ['recipient_id', 'is_read'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index('ix_offer_buyer_status', ['buyer_id', 'status'], unique=False)
        batch_op.create_index('ix_offer_listing_buyer', ['listing_id', 'buyer_id'], unique=False)

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index('ix_proposal_gig_status', ['gig_id', 'status'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewee_id'), ['reviewee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('showcase_comments', schema=None) as batch_op:
        batch_op.create_index('ix_showcase_comment_post', ['post_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_showcase_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_showcase_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('showcase_likes', schema=None) as batch_op:
        batch_op.create_index('ix_showcase_like_post_user', ['post_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_showcase_likes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_showcase_likes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transaction_buyer_status', ['buyer_id', 'status'], unique=False)
        batch_op.create_index('ix_transaction_context', ['context_type', 'context_id'], unique=False)
        batch_op.create_index('ix_transaction_seller_status', ['seller_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_auto_release_at'), ['auto_release_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_context_type'), ['context_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_gig_id'), ['gig_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_released_at'), ['released_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_released_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_paid_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_listing_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_gig_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_context_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_auto_release_at'))
        batch_op.drop_index('ix_transaction_seller_status')
        batch_op.drop_index('ix_transaction_context')
        batch_op.drop_index('ix_transaction_buyer_status')

    with op.batch_alter_table('showcase_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_showcase_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_showcase_likes_post_id'))
        batch_op.drop_index('ix_showcase_like_post_user')

    with op.batch_alter_table('showcase_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_showcase_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_showcase_comments_post_id'))
        batch_op.drop_index('ix_showcase_comment_post')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_reviewee_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_proposal_gig_status')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index('ix_offer_listing_buyer')
        batch_op.drop_index('ix_offer_buyer_status')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index('ix_notification_user_read')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_message_recipient_read')
        batch_op.drop_index('ix_message_participants')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listing_seller_status')
        batch_op.drop_index('ix_listing_category_status')

    with op.batch_alter_table('gigs', schema=None) as batch_op:
        batch_op.drop_index('ix_gig_client_status')
        batch_op.drop_index('ix_gig_category_status')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_target_type'))
        batch_op.drop_index(batch_op.f('ix_reports_target_id'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))

    op.drop_table('reports')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
